Use MyTunes
-- Drops all of the talbes in correct order
DROP TABLE IF EXISTS Song_playlist_relation;
DROP TABLE IF EXISTS Playlists
DROP TABLE IF EXISTS Song_album_relation;
DROP TABLE IF EXISTS Song_artist_relation;
DROP TABLE IF EXISTS Song_data;
DROP TABLE IF EXISTS Songs;
DROP TABLE IF EXISTS Albums;
DROP TABLE IF EXISTS Artists;
DROP TABLE IF Exists Users;

-- Creates all of the tables
CREATE TABLE Users(
	[Id] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	[Name] NVARCHAR(255) NOT NULL
)
INSERT INTO Users (Name) Values ('Default')

CREATE TABLE Artists(
    [Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    [Name] NVARCHAR(255) NOT NULL
)

CREATE TABLE Albums(
    [Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    [Name] NVARCHAR(255) NOT NULL
)

CREATE TABLE Songs(
    [Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    [Title] NVARCHAR(255) NOT NULL,
	[Data] VARBINARY(MAX) NOT NULL,
	[Playtime] INT NOT NULL DEFAULT 0
)

CREATE TABLE Song_Artist_Relation(
    [Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    [SongId] INT FOREIGN KEY REFERENCES [Songs](Id) NOT NULL,
    [ArtistId] INT FOREIGN KEY REFERENCES [Artists](Id) NOT NULL
)

CREATE TABLE Song_Album_Relation(
    [Id] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    [SongId] INT FOREIGN KEY REFERENCES [Songs](Id) NOT NULL,
    [AlbumId] INT FOREIGN KEY REFERENCES [Albums](Id) NOT NULL
)

CREATE TABLE Playlists(
    [Id] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	[UserID] INT FOREIGN KEY REFERENCES [Users](Id),
    [Name] NVARCHAR(255) NOT NULL,
	[Date] DATETIME DEFAULT GETUTCDATE(),
	[Playtime] INT NOT NULL DEFAULT 0
)

CREATE TABLE Song_Playlist_Relation(
    [Id] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    [SongId] INT FOREIGN KEY REFERENCES [Songs](id) NOT NULL,
    [PlaylistId] INT FOREIGN KEY REFERENCES [Playlists](id) NOT NULL,
	[Position] INT NOT NULL,
    [Date_Added] DATETIME DEFAULT GETUTCDATE() NOT NULL
)

